export const FETCH_CURRENT_WEATHER_SUCCESS = "FETCH_CURRENT_WEATHER_SUCCESS";
export const FETCH_FORCAST_WEATHER_SUCCESS = "FETCH_FORCAST_WEATHER_SUCCESS";
export const SET_CITY = "SET_CITY";
export const FETCH_CURRENT_WEATHER_ERROR = "FETCH_CURRENT_WEATHER_ERROR";
export const FETCH_FORCAST_WEATHER_ERROR = "FETCH_FORCAST_WEATHER_ERROR";
export const FETCH_CURRENT_WEATHER_PENDING = "FETCH_CURRENT_WEATHER_PENDING";
export const FETCH_FORCAST_WEATHER_PENDING = "FETCH_FORCAST_WEATHER_PENDING";
